# cSpell:disable
# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.36.1"
"rocks-config.nvim" = "2.2.0"
gruvbox-baby = "0.1.8"
cmp-nvim-lsp = "scm"
cmp-buffer = "scm"
cmp-path = "scm"
cmp-cmdline = "scm"
nvim-cmp = "0.0.1"
copilot-cmp = "scm"
"oil.nvim" = "2.11.0"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.29.0"
"telescope.nvim" = "scm"
"telescope-zf-native.nvim" = "1.0.0"
"which-key.nvim" = "3.13.2"
"conform.nvim" = "7.0.0"
"rocks-git.nvim" = "2.0.1"
"zen-mode.nvim" = "1.4.0"
"dressing.nvim" = "2.2.2"
nvim-lint = "scm"
nvim-ufo = "1.4.0"
nvim-spectre = "scm"
"statuscol.nvim" = "scm"
"lsp-zero.nvim" = "scm"
"typescript-tools.nvim" = "scm"
rustaceanvim = "5.1.1"
nvim-autopairs = "scm"
nvim-ts-autotag = "scm"
nvim-ts-context-commentstring = "scm"
"diffview.nvim" = "scm"
"lazygit.nvim" = "scm"
cmp_luasnip = "scm"
friendly-snippets = "scm"
luasnip = "2.3.0"
"copilot.lua" = "scm"

[plugins."debugprint.nvim"]
git = "andrewferrier/debugprint.nvim"
rev = "v3.1.0"

[plugins."nvim-treesitter"]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugin."nvim-cmp"]
git = "hrsh7th/nvim-cmp"
branch = "main"

[plugin."copilot.lua"]
git = "zbirenbaum/copilot.lua"
branch = "master"

[bundles.cmp] # Create a bundle called `cmp`
items = [
  "cmp-nvim-lsp",
  "cmp-buffer",
  "cmp-path",
  "cmp-cmdline",
  "nvim-cmp",
  "luasnip",
  "cmp_luasnip",
  "friendly-snippets",
]

[bundles.lsp]
items = ["lsp-zero.nvim", "rustaceanvim", "typescript-tools.nvim"]

# [bundles.copilot]
# items = ["copilot.lua", "copilot-cmp"]
